import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "@/components/nav"
import localFont from "next/font/local"

import { FlipLinkNav, FlipLink } from "@/components/flipLink"
import Link from "next/link"
import ToMail from "@/components/email-button"
import SecondNav from "@/components/secondNav"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "lolooooooo",
  description: "Generated by create next app",
}

const NanoFont = localFont({
  src: '../../public/fonts/NaNHoloGigawide-Ultra.ttf',
  weight: '400',
  variable: '--font-nano',
})
const MarioFont = localFont({
  src: '../../public/fonts/Mario-Regular.otf',
  weight: '400',
  variable: '--font-Mario',
})
const GatwickVariable = localFont({
  src: '../../public/fonts/Gatwick-Variable.ttf',
  weight: '1 999',
  variable: '--font-Gatwick',
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen">
      <script async src="http://lolowebsite-umami-73934c-116-203-132-182.traefik.me/script.js"
        data-website-id="256eb5ab-4dcb-44d2-a94c-9b7a6834b4c2"
      />
      <body className={`${NanoFont.className} `}>
        <SecondNav />
        <Nav />
        {children}
        <footer className={GatwickVariable.className}>
          <div className="w-full flexitems-left justify-between text-2xl ml-2 items-center">
            <span className="sm:text-center">© 2024 </span> <span>
              <a href="https://cgidoggs.world//" className="hover:underline">cgistudio</a>.love
            </span>
          </div>
        </footer>

      </body>
    </html>
  )
}
