import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "@/components/nav"
import localFont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "lolooooooo",
  description: "Generated by create next app",
}

const NanoFont = localFont({ 
  src: '../../public/fonts/NaNHoloGigawide-Ultra.ttf', 
  weight: '700', 
  variable: '--font-nano',
})
const MarioFont = localFont({ 
  src: '../../public/fonts/Mario-Regular.otf', 
  weight: '700', 
  variable: '--font-Mario',
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={NanoFont.className}>
          <Nav />
        {children}
        <footer className={MarioFont.className}>
          <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-left md:justify-between text-2xl">
            <span className="sm:text-center">© 2024 </span> <span>
              <a href="https://cgidoggs.world//" className="hover:underline">cgistudio</a>. All Rights Reserved.
            </span>
            <ul className="flex flex-wrap items-center ">
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
