"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AllSpikeAnim(props) {

  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/allSpikeHeadAnim.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => void (actions.spikeHeadLooking.reset().play().paused = false), [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        
        <mesh
          name="mesh"
          castShadow
          receiveShadow
          geometry={nodes.mesh.geometry}
          material={materials.material}
          position={[-0.269, 0.174, -0.002]}
        />
        <mesh
          name="mesh001"
          castShadow
          receiveShadow
          geometry={nodes.mesh001.geometry}
          material={materials['material.002']}
          position={[0.517, 0, 0]}
        />
        <mesh
          name="mesh002"
          castShadow
          receiveShadow
          geometry={nodes.mesh002.geometry}
          material={materials['material.005']}
        />
        <group
          name="spikeHeadBones"
          position={[0.241, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
          <skinnedMesh
            name="SpikeHead001"
            geometry={nodes.SpikeHead001.geometry}
            material={materials['Material_0.001']}
            skeleton={nodes.SpikeHead001.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/allSpikeHeadAnim.glb')
