"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"


export function Model(props) {

  const group = useRef()
  const scroll = useScroll()

  const { nodes, materials, animations } = useGLTF('/spikeHeadAnim.glb')

  const {  actions } = useAnimations(animations, group)
  

  useEffect(() => void (actions.spikeHeadLooking.reset().play().paused = false), [])
  // useFrame(() => (actions.spikeHeadLooking.time = actions.spikeHeadLooking.getClip().duration * scroll.offset))



  return (

    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="spikeHeadBones" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="SpikeHead001"
            geometry={nodes.SpikeHead001.geometry}
            material={materials.Material_0}
            skeleton={nodes.SpikeHead001.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spikeHeadAnim.glb')
