"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

import { useGLTF } from '@react-three/drei'

export default function Tito(props) {

  const tito_ref = useRef()

  useFrame((state, delta) => {
    tito_ref.current.rotation.y += delta * 0.2
  })


  const { nodes, materials } = useGLTF('./Tito.glb') 
  return (
    <group ref={tito_ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TitoBlend.geometry}
        material={materials.Material_0}
      />
    </group>
    
  )
}

useGLTF.preload('./Tito.glb')
