"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tito(props) {
  const { nodes, materials } = useGLTF('./Tito.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TitoBlend.geometry}
        material={materials.Material_0}
      />
    </group>
  )
}

useGLTF.preload('./Tito.glb')
